#!/bin/bash

# Ugly stuff to get base dir
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [ $# -lt 1 ];
    then echo "Usage: nrk-download url"
    exit
fi

# Parse the feed
data=`php $DIR/lib/parse-markup.php $1`

# Split the parser response by whitespace
IFS=" " read key stream subtitle <<< "$data"

# Create destination folder
createFolderResult=`php $DIR/lib/create-dst-folder.php $key`

# Download the subtitles
subtitleResult=`php $DIR/lib/download-subtitle.php $key $subtitle`

convertStream() {
    if hash aconv 2>/dev/null; then
        aconv "$@"
    else
        ffmpeg "$@"
    fi
}

# Check if subtitle was found
if [ "$subtitle" != "" ]; then
    # Download stream and add subtitle
    convertStream -i $stream -i "$key.nb.srt" -scodec srt -map 0:v -map 0:a -map 1 -c:v copy -flags global_header $key.mkv
else
    # Download stream
    convertStream -i $stream -map 0:v -map 0:a -map 1 -c:v copy -flags global_header $key.mkv
fi

# Remove srt file
rm $key.nb.srt

ls -l $key*
